### PR TITLE
Fix compilation error with Qt 5.8, resolves #195

### LINKED ISSUE #195: Doesn't compile with Qt 5.8 RC
<!--- Provide a general summary of the issue in the title above -->
On building Keepassxc on Arch Linux from the AUR package keepassxc-git with the  5.8 Release Candidate version of QT (from Arch's `testing` repository), the following message pops up while compiling:

```[ 29%] Building CXX object src/CMakeFiles/keepassx_core.dir/format/KeePass2XmlReader.cpp.o                                                                              
/home/dominik/.tmp/yaourt/yaourt-tmp-dominik/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp: In member function 'void KeePass2XmlReader::parseBinaries()':
/home/dominik/.tmp/yaourt/yaourt-tmp-dominik/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp:391:77: error: call of overloaded 'compare(const char [5], Qt::CaseSensitivity)' is ambiguous
           if (attr.value("Compressed").compare("True", Qt::CaseInsensitive) == 0) {
                                                                           ^
In file included from /usr/include/qt/QtCore/qregexp.h:47:0,
                 from /usr/include/qt/QtCore/qstringlist.h:47,
                 from /usr/include/qt/QtCore/qlist.h:1093,
                 from /usr/include/qt/QtCore/qstringlist.h:41,
                 from /usr/include/qt/QtGui/qcolor.h:46,
                 from /usr/include/qt/QtGui/QColor:1,
                 from /home/dominik/.tmp/yaourt/yaourt-tmp-dominik/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.h:21,
                 from /home/dominik/.tmp/yaourt/yaourt-tmp-dominik/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp:18:
/usr/include/qt/QtCore/qstring.h:1584:12: note: candidate: int QStringRef::compare(const QString&, Qt::CaseSensitivity) const
 inline int QStringRef::compare(const QString &s, Qt::CaseSensitivity cs) const Q_DECL_NOTHROW
            ^~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1515:9: note: candidate: int QStringRef::compare(const QByteArray&, Qt::CaseSensitivity) const
     int compare(const QByteArray &s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
         ^~~~~~~
make[2]: *** [src/CMakeFiles/keepassx_core.dir/build.make:903: src/CMakeFiles/keepassx_core.dir/format/KeePass2XmlReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:257: src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build keepassxc-git.
```

Relevant output from `qtdiag-qt5` is as follows:

```
Qt 5.8.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.3.1 20170109) on "xcb"                                                                  
OS: Arch Linux [linux version 4.9.5-1-ARCH]                                                                                                                          
                                                                                                                                                                     
Architecture: x86_64; features: SSE2 SSE3 SSSE3                                                                                                                      
                                                                                                                                                                     
Environment:                                                                                                                                                         
  QT_AUTO_SCREEN_SCALE_FACTOR="0"                                                                                                                                    
                                                                                                                                                                     
Features: QT_NO_EXCEPTIONS  
```

I'm not sure whether this issue will continue occurring in Qt 5.8 proper, but I've seen this noted on [the keepassxc AUR page](https://aur.archlinux.org/packages/keepassxc/) and felt it was best to note it here.

### PR DESCRIPTION
**Pull request by phoerious**
## Description

This is cherry-pick of commit https://github.com/keepassx/keepassx/commit/8cd0c8555413a6bdf4b6603211cf3b930a1036a0 in KeePassX which fixes a compilation error with Qt 5.8.

This pull request resolves #195.

## How Has This Been Tested?

All tests pass, code still compiles.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Will cherry-picking like this diverge KeePassXC more from the KeePassX repository? Shouldn't we merge his commit as-is?

**Comment by phoerious** [comment]
The keepassx master branch isn't cleanly mergable onto our branches which is why I cherry-picked. I also didn't want any of the follow-up merge commits. I could have also just copied the fix and committed it myself, but wanted to preserve the original author of the commit.

**Comment by TheZ3ro** [comment]
If we will merge in the future we must preserve commit as-is like in the Yubikey branch.

**Comment by phoerious** [comment]
I can't merge the keepassx branch upwards without solving tons of merge conflicts. I could try a rebase --onto, but that also doesn't preserve history.

**Comment by TheZ3ro** [comment]
So I think we will address this problem when we will merge in the future

**Comment by phoerious** [comment]
The common ancestor of our master branch and the keepassx master branch is 878995366aacf55bdff7e7fc9274073aca9d4c87. Since then there are 80 diverged commits on KeePassX which need manual merging before we have a clean common ancestor again.
