### ISSUE TITLE
Snap Regression: v28 text does not render

### ISSUE THREAD

**Issue by M-Pixel** [keepassxreboot/keepassxc#1292]
## Expected Behavior
~KeePassXC scales everything 2x because I have configured a 2x display scaling factor in my KDE settings.~

KeePassXC's user interface has text on buttons, labels, etc.

## Current Behavior
~UI widgets are scaled 2x, and then everything inside of them is scaled an additional 2x, and a lot of the text does not appear at all.~

KeePassXC renders widgets and icons, but not text.

## Context
This started ocurring as soon as Snap Daemon updated `keepassxc` from version **26** to version **28**. `snap revert keepassxc` fixed the problem, indicating that it's the update of KeePassXC itself and not Snap or some other package on my computer that is causing this problem.

~Version 28 does not have this problem on my other computer, which does not have a scaling factor configured.~

_^ The above was a mistaken observation - I had updated KeePassXC, but was still running the older version._

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66
Distribution: Snap

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: openSUSE Leap 42.3
CPU architecture: x86_64
Kernel: linux 4.4.103-2.g70b1a87-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is likely caused by my upgrading to Ubuntu 17.10, realizing snaps can't be built in 17.10 (omg..), then running "buildclean" which builds the snap in a 16.04 container. This means the qt version packaged with the snap is too old to handle scaling.

**Comment by M-Pixel** [comment]
After a bit more troubleshooting, I have better info:

The issue has nothing to do with DPI scaling - it occurs on computers with and without scaling.

The issue is that **text** is not rendered at all.

![screenshot_20171216_150015](https://user-images.githubusercontent.com/4174312/34075135-07dea39c-e272-11e7-86d4-b8bae93d7b6e.png)

**Comment by pachulo** [comment]
@droidmonkey Could this be related to the fact that keepassx is using modified `stage-packages` for part `desktop-qt5`? https://github.com/keepassxreboot/keepassxc/commit/b8028ff3 

I guess you did that change to be able to compile the snap with Ubuntu 17.04, but, as you said, now with `snapcraft cleanbuild` you're back at compiling in a Ubuntu 16.04 environment.

Also, the `stage-packages` from the part have diverged https://github.com/Ubuntu/snapcraft-desktop-helpers/blame/master/snapcraft.yaml#L222

**Comment by droidmonkey** [comment]
Oh great find @pachulo, looks like I can completely remove the redefinition of stage-packages now.

**Comment by droidmonkey** [comment]
I pushed a new snap build (29) built against 17.04 and the updated packages for desktop-qt5. Can you guys please test against it?

**Comment by pachulo** [comment]
Just out of curiosity @droidmonkey : Why is there the need to compile with 17.04? Does Keepassxc needs Qt 5.7.1 or higher?

**Comment by droidmonkey** [comment]
There are significant performance and visual differences between the 5.x qt lines.
