### PR TITLE
fix build with botan 3.11

### LINKED ISSUE #13160: Arch linux / error while loading shared libraries: libbotan-3.so.10: cannot open shared object file: No such file or directory
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

After updating my cachyos  keepassxc from develop branch stopped working due to incompatible botan dependency.

```
❯keepassxc
keepassxc: error while loading shared libraries: libbotan-3.so.10: cannot open shared object file: No such file or directory
```

When trying to recompile from develop branch:
```
/home/michau/bin/keepassxc/src/sshagent/OpenSSHKeyGen.cpp: In function ‘bool OpenSSHKeyGen::generateECDSA(OpenSSHKey&, int)’:
/home/michau/bin/keepassxc/src/sshagent/OpenSSHKeyGen.cpp:91:43: error: variable ‘Botan::EC_Group domain’ has initializer but incomplete type
   91 |             Botan::EC_Group domain(QString("secp%1r1").arg(bits).toStdString());
      |                                           ^
make[2]: *** [src/sshagent/CMakeFiles/sshagent.dir/build.make:184: src/sshagent/CMakeFiles/sshagent.dir/OpenSSHKeyGen.cpp.o] Błąd 1
make[2]: *** Oczekiwanie na niezakończone zadania....
```

Using botan 3.11.0-1.1.
```
❯ pacman -Qi botan
Zainstalowano z       : cachyos-extra-v3
Nazwa                 : botan
Wersja                : 3.11.0-1.1
Opis                  : Crypto library written in C++
Architektura          : x86_64_v3
Adres url             : https://botan.randombit.net/
Licencje              : BSD-2-Clause
Grupy                 : Brak
Dostarcza             : Brak
Zależy od             : bzip2  gcc-libs  glibc  sqlite  xz  zlib
Opcjonalne zależności : boost-libs: for the botan executable [zainstalowano]
                        python: for using botan2.py [zainstalowano]
Wymagany przez        : Brak
Opcjonalny dla        : qca-qt6
Konfliktuje z         : Brak
Zastępuje             : Brak
Rozmiar po instalacji : 13,20 MiB
Autor pakietu         : CachyOS <admin@cachyos.org>
Data zbudowania       : pon, 16 mar 2026, 00:46:45
Data zainstalowania   : pon, 16 mar 2026, 13:10:27
Powód zainstalowania  : Ręczny
Skrypt instalacyjny   : Nie
Potwierdzone przez    : Podpis
```

I fixed this issue by adding `#include <botan/ec_group.h>` in `OpenSSHKeyGen.cpp`. But I'm not C++ dev.

### Expected Versus Actual Behavior

_No response_

### Steps to Reproduce

1. Using cachy os use sudo pacman -Syu
2. keepassxc from develop branch will stop running.

### KeePassXC-Browser Debug Information

```Text

```

### PR DESCRIPTION
**Pull request by Zebra2711**
adding missing <botan/ec_group.h> include for botan 3.11

Fixes #13160 

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by Zebra2711** [comment]
~I don’t know why Archlinux ships botan to extra without rebuilding keepassxc.~
```
$ pactree -rc botan -d 1
botan
├─keepassxc
└─thunderbird
```

**Review by droidmonkey — APPROVED** [review]

**Comment by jketema** [comment]
@droidmonkey Any chance this can get merged? We build keepassxc on macOS during some of our internal testing, and that's currently broken due to this.

**Comment by droidmonkey** [comment]
@jketema sorry for delay, merged

**Comment by jketema** [comment]
Thank you! 🎉
