### ISSUE TITLE
Build failure without WITH_XC_KEESHARE=ON

### ISSUE THREAD

**Issue by bosth** [keepassxreboot/keepassxc#2840]
The 2.4.0 build fails without `WITH_XC_KEESHARE=ON`. The same build parameters worked on 2.3.x.

CMake options:
```
cmake \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_TESTS=OFF \
  -DWITH_XC_BROWSER=ON \
  -DWITH_XC_YUBIKEY=OFF \
  -DWITH_XC_NETWORKING=ON \
  -DWITH_XC_AUTOTYPE=ON \
  -DWITH_XC_SSHAGENT=ON \
  ..

make
```

## Current Behavior
```
[ 41%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/CategoryListWidget.cpp.o
[ 41%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/Clipboard.cpp.o
[ 42%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/CloneDialog.cpp.o
[ 42%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/DatabaseOpenWidget.cpp.o
[ 42%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/DatabaseTabWidget.cpp.o
[ 43%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/DatabaseWidget.cpp.o
keepassxc-2.4.0/src/gui/DatabaseWidget.cpp: In member function ‘void DatabaseWidget::search(const QString&)’:
keepassxc-2.4.0/src/gui/DatabaseWidget.cpp:1115:5: error: ‘m_shareLabel’ was not declared in this scope
     m_shareLabel->setVisible(false);
     ^~~~~~~~~~~~
keepassxc-2.4.0/src/gui/DatabaseWidget.cpp:1115:5: note: suggested alternative: ‘m_searchingLabel’
     m_shareLabel->setVisible(false);
     ^~~~~~~~~~~~
     m_searchingLabel
make[2]: *** [src/CMakeFiles/keepassx_core.dir/build.make:856: src/CMakeFiles/keepassx_core.dir/gui/DatabaseWidget.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:199: src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

## Possible Solution
Adding `WITH_XC_KEESHARE=ON` solves the build error.

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Slackware 14.2 x86_64 (post 14.2 -current)
CPU architecture: x86_64
Kernel: linux 4.19.21

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)

**Comment by droidmonkey** [comment]
Duplicate.
