### PR TITLE
use setWindowFlags() instead of setWindowFlag on Qt<5.9

### PR DESCRIPTION
**Pull request by tenzap**
Fixes this error when building with Qt <5.9
This also applies to 2.7 branch

src/gui/CloneDialog.cpp:32:5: error: use of undeclared identifier 'setWindowFlag'
    setWindowFlag(Qt::WindowContextHelpButtonHint, false);
    ^

void QWidget::setWindowFlag(Qt::WindowType flag, bool on = true) --> This function was introduced in Qt 5.9.

---

Instead of `#if`, an alternative would be to use the statement for Qt<5.9 in all cases, which would permit to remove the `#if`...

That would be just replace:
```
setWindowFlag(Qt::WindowContextHelpButtonHint, false);
```
by
```
setWindowFlags(windowFlags() & ~Qt::WindowContextHelpButtonHint);
```

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
Builds fine on macports with qt < 5.9
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I am only merging this one to 2.7.x branch. The develop branch will be migrated to Qt 6
