### ISSUE TITLE
TagsEdit.cpp: won't compile on Ubuntu 16.04 with gcc 5.4.0

### ISSUE THREAD

**Issue by DeckerSU** [keepassxreboot/keepassxc#7678]
Try to compile 4178e72fe04eb97d0787c006b03993c87baa26c3 on Ubuntu 16.04 with gcc 5.4.0 gives the following error(s):
```
TagsEdit.cpp:132:75: error: expected constructor, destructor, or type conversion before ‘;’ token
     template <class It> EmptySkipIterator(It, It) -> EmptySkipIterator<It>;
```
and
```
TagsEdit.cpp:343:111: error: cannot call member function ‘QString& TagsEdit::Impl::currentText()’ without object
```
Here is workaround to get it compiled:
```
diff --git a/src/gui/tag/TagsEdit.cpp b/src/gui/tag/TagsEdit.cpp
index b4bfb7f7..8956168b 100644
--- a/src/gui/tag/TagsEdit.cpp
+++ b/src/gui/tag/TagsEdit.cpp
@@ -73,7 +73,7 @@ namespace
         EmptySkipIterator() = default;
 
         // skip until `end`
-        explicit EmptySkipIterator(It it, It end)
+        explicit EmptySkipIterator(It it, It end) 
             : it(it)
             , end(end)
         {
@@ -129,7 +129,7 @@ namespace
         It end;
     };
 
-    template <class It> EmptySkipIterator(It, It) -> EmptySkipIterator<It>;
+    // template <class It> EmptySkipIterator(It, It) -> EmptySkipIterator<It>;
 
 } // namespace
 
@@ -340,7 +340,8 @@ struct TagsEdit::Impl
     {
         assert(i < tags.size());
         auto occurrencesOfCurrentText =
-            std::count_if(tags.cbegin(), tags.cend(), [this](const auto& tag) { return tag.text == currentText(); });
+            std::count_if(tags.cbegin(), tags.cend(), [this](const auto& tag) { return tag.text == this->currentText(); });
+
         if (currentText().isEmpty() || occurrencesOfCurrentText > 1) {
             tags.erase(std::next(tags.begin(), std::ptrdiff_t(editing_index)));
             if (editing_index <= i) { // Do we shift positions after `i`?
@@ -678,9 +679,9 @@ void TagsEdit::paintEvent(QPaintEvent*)
             p,
             std::make_pair(std::next(impl->tags.cbegin(), std::ptrdiff_t(impl->editing_index + 1)), impl->tags.cend()));
     } else {
-        impl->drawTags(p,
-                       std::make_pair(EmptySkipIterator(impl->tags.begin(), impl->tags.end()),
-                                      EmptySkipIterator(impl->tags.end())));
+        auto p1 = EmptySkipIterator<decltype(impl->tags.begin())>(impl->tags.begin(), impl->tags.end());
+        auto p2 = EmptySkipIterator<decltype(impl->tags.end())>(impl->tags.end());
+        impl->drawTags(p, std::make_pair(p1,p2));
     }
 }
 
@@ -893,8 +894,10 @@ void TagsEdit::tags(QStringList const& tags)
     impl->editing_index = 0;
     QList<Tag> t{Tag()};
 
-    std::transform(EmptySkipIterator(tags.begin(), tags.end()), // Ensure Invariant-1
-                   EmptySkipIterator(tags.end()),
+    auto p1 = EmptySkipIterator<decltype(tags.begin())>(tags.begin(), tags.end());
+    auto p2 = EmptySkipIterator<decltype(tags.end())>(tags.end());
+    std::transform(p1, // Ensure Invariant-1
+                   p2,
                    std::back_inserter(t),
                    [](QString const& text) {
                        return Tag{text, QRect(), 0};
@@ -911,8 +914,9 @@ void TagsEdit::tags(QStringList const& tags)
 QStringList TagsEdit::tags() const
 {
     QStringList ret;
-    std::transform(EmptySkipIterator(impl->tags.begin(), impl->tags.end()),
-                   EmptySkipIterator(impl->tags.end()),
+    auto p1 = EmptySkipIterator<decltype(impl->tags.begin())>(impl->tags.begin(), impl->tags.end());
+    auto p2 = EmptySkipIterator<decltype(impl->tags.end())>(impl->tags.end());
+    std::transform(p1, p2,
                    std::back_inserter(ret),
                    [](Tag const& tag) { return tag.text; });
     return ret;
```
Maybe this patch will help somebody.

**Comment by phoerious** [comment]
Sorry, but we don't support Ubuntu 16.04 anymore.
