### ISSUE TITLE
KEEPASSXC-BROWSER: cannot connect to database 

### ISSUE THREAD

**Issue by frenciszak** [keepassxreboot/keepassxc#9291]
## Overview
When make sure KeePassXC running and database is open 
Then opening browser and trying to connect extension results in infinite loading

## Steps to Reproduce
1.  Make sure KeePassXC application is running and database is open
2.  Make sure integration with browser is turned on in the application and extension is install in the browser
3. Open browser with extension
4. Click extension icon and choose to connect to database

## Expected Behavior
Extension is connected to database
Login info can be filled in forms from DB

## Actual Behavior

Checking status...................................................................................................................................................................................

```
Uncaught (in promise) Error: Object.hasOwn is not a function
    at n (browser-polyfill.min.js:1)
```

## Context
The following error occurs when open extension settings page 
_Error loading options page: Error: Object.hasOwn is not a function_

Left navigation does not work in settings

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Browser: Chromium based ( Iron  Version 90.0.4600.0 (Official Build) (64-bit) )

**Comment by droidmonkey** [comment]
You need to update your browser

**Comment by frenciszak** [comment]
Thank you very much for your comment. It's like f ** k you only shorter. I do have this version of the browser for a reason. 
You could point me to the list of supported browsers, you could point me to announcement that the extension will drop some browser versions in some time. But you don't have this. Suddenly what worked in 90.0.4600.0 just stops working and you don't give a f ** k about those who use it. It's theirs fault anyway, not you miscommunications. Yep, you don't have time for it !

**Comment by droidmonkey** [comment]
That's what happens when you use unsupported software 🫡

Chromium version 90 hasn't been supported when it comes to security patches for around 2 years. Needless to say that is not a good thing for your overall security posture.
