### PR TITLE
Replace legacy code on macOS builds

### LINKED ISSUE #11288: Failed build on macOS with Xcode 16.0
```
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_security_KeePassXC/KeePassXC/work/keepassxc-c1a66a8be98d8f3a7ea1ba0ca6065c2d1a10e56b/src/gui/osutils/macutils/AppKitImpl.mm:190:37: error: 'CGDisplayStreamCreate' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
:info:build   190 |         CGDisplayStreamRef stream = CGDisplayStreamCreate(CGMainDisplayID(), 1, 1, kCVPixelFormatType_32BGRA, nil,
:info:build       |                                     ^
:info:build /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayStream.h:242:41: note: 'CGDisplayStreamCreate' has been explicitly marked unavailable here
```

refer to: https://github.com/keepassxreboot/keepassxc/discussions/10308

### PR DESCRIPTION
**Pull request by FischLu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

fix #11288, The CGDisplayStreamCreate function has been deprecated and the current code fails to compile on macOS 15 and above. Following Apple's official recommendations, this fix replaces CGDisplayStreamCreate with ScreenCaptureKit (MacOS 12.3+). Since ScreenCaptureKit is an asynchronous framework, necessary semaphore waiting has been added to the code. This change successfully triggers the screen recording permission request dialog and allows proper use of autotype when permission is granted. The code has been tested and confirmed working on macOS 15.0.1.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Omg thank you, I really didn't want to figure this one out.

File: src/gui/osutils/macutils/AppKitImpl.mm [hunk 1]
```diff
@@ -181,28 +184,36 @@ - (bool) enableAccessibility
...
-            return NO;
-        }
+#if __clang_major__ >= 13 && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_VERSION_12_3
+    if (@available(macOS 12.3, *)) {
+        __block BOOL hasPermission = NO;
+        dispatch_semaphore_t sema = dispatch_semaphore_create(0);
+
+        // Attempt to use SCShareableContent to check for screen recording permission
+        [SCShareableContent getShareableContentWithCompletionHandler:^(SCShareableContent * _Nullable content, 
+                                                                        NSError * _Nullable error) {
```
Comment (varjolintu) [inline src/gui/osutils/macutils/AppKitImpl.mm:196]: You must use `Q_UNUSED(error)` for the second parameter. Otherwise the code will not compile.

Comment (FischLu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: It's compilable; otherwise, I wouldn't be able to test if the screen recording permission request dialog works properly. Additionally, the automated tests didn't report any errors. However, if you believe that adding Q_UNUSED(error) can improve the code's robustness, then it can certainly be included.

Comment (droidmonkey) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: Q_UNUSED is only useful on Linux where GCC and Clang complain of unused parameters.

Comment (varjolintu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: I tested this with both macOS Sequoia and Sonoma. Disabled the setting in the System Preferences and then I didn't have a permission to perform Global Auto-Type.

Only complained about `Q_UNUSED()` because the compiler gives me an error, not a warning.

Comment (FischLu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: have you just disable the old permission or complete remove it? In my case macOS Sequoia just disable is not enough, I need to remove the keepassxc from privacy setting, then I see the dialog, after permit, the keepassxc is added to the list again.

image

Comment (varjolintu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: If just disabling the setting does not work properly then there must be something missing?

Comment (FischLu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: it's Macos problem, I have same story of some screenshot apps, I think it's about signature of software maybe....

Comment (FischLu) [reply src/gui/osutils/macutils/AppKitImpl.mm:196]: I just tested it, for the current official release 2.7.9, the behavior is the same, just disabling the setting does not work.

**Comment by FischLu** [comment]
After adding Q_UNUSED(error), the automated tests do not pass. You may check the reason.

**Comment by droidmonkey** [comment]
The failures are ephermal and unrelated

**Review by droidmonkey — APPROVED** [review]

**Comment by TheRojam** [comment]
Thank you guys!
