### PR TITLE
:bug: Fix building with Qt 5.9 (closes #528)

### LINKED ISSUE #528: Fail to build with Qt 5.9 beta 2
## Expected Behavior

KeepassXC builds fine even with the latest beta preview of Qt

## Current Behavior

```
[ 73%] Linking CXX executable testentrymodel
cd /home/yen/Projects/tmp/keepassxc/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/testentrymodel.dir/link.txt --verbose=1
/usr/bin/c++   -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -pie -fPIE -std=c++11 -O2 -g -DNDEBUG   -Wl,--no-add-needed -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro,-z,now -rdynamic CMakeFiles/testentrymodel.dir/TestEntryModel.cpp.o CMakeFiles/testentrymodel.dir/testentrymodel_autogen/moc_compilation.cpp.o  -o testentrymodel libtestsupport.a ../src/libkeepassx_core.a /usr/lib/libQt5Concurrent.so.5.9.0 /usr/lib/libQt5Test.so.5.9.0 -lgcrypt -lgpg-error -lz ../src/libautotype.a /usr/lib/libQt5Widgets.so.5.9.0 /usr/lib/libQt5Gui.so.5.9.0 ../src/libzxcvbn.a /usr/lib/libQt5DBus.so.5.9.0 /usr/lib/libQt5Core.so.5.9.0
libtestsupport.a(modeltest.cpp.o): In function `ModelTest::data()':
/home/yen/Projects/tmp/keepassxc/tests/modeltest.cpp:451: undefined reference to `bool QTest::qCompare<int, unsigned int>(int const&, unsigned int const&, char const*, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/testentrymodel.dir/build.make:134: tests/testentrymodel] Error 1
make[2]: Leaving directory '/home/yen/Projects/tmp/keepassxc'
make[1]: *** [CMakeFiles/Makefile2:1175: tests/CMakeFiles/testentrymodel.dir/all] Error 2
make[1]: Leaving directory '/home/yen/Projects/tmp/keepassxc'
make: *** [Makefile:141: all] Error 2
```
## Possible Solution

Inspired by http://stackoverflow.com/a/14198973/3786245, I force the second to be int:
```Diff
diff --git a/tests/modeltest.cpp b/tests/modeltest.cpp
index 360a7be..0792e4f 100644
--- a/tests/modeltest.cpp
+++ b/tests/modeltest.cpp
@@ -448,7 +448,7 @@ void ModelTest::data()
     QVariant textAlignmentVariant = model->data ( model->index ( 0, 0 ), Qt::TextAlignmentRole );
     if ( textAlignmentVariant.isValid() ) {
         int alignment = textAlignmentVariant.toInt();
-        QCOMPARE( alignment, ( alignment & ( Qt::AlignHorizontal_Mask | Qt::AlignVertical_Mask ) ) );
+        QCOMPARE( alignment, static_cast<int>( alignment & ( Qt::AlignHorizontal_Mask | Qt::AlignVertical_Mask ) ) );
     }
 
     // General Purpose roles that should return a QColor
``` 

## Steps to Reproduce (for bugs)

1. git clone keepassxc
2. cmake .
3. make

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) ad79162061c19decdd122784ff8adc4f18d6ce9b
* Qt version (e.g. Qt 5.3): Qt 5.9 beta 2
* Compiler (e.g. Clang++3.6.0): GCC 6.3.1
* Operating System and version: Arch Linux x86_64 (with [kde-unstable] repository enabled)

### PR DESCRIPTION
**Pull request by yan12125**
## Description

Qt's QCOMPARE() is never well-defined. In some Qt versions it requires RHS and LHS to have exactly the same type while some versions just ask for comparable types. In Qt 5.9, there's a new breakage here.

## Motivation and context

Homebrew has updated to Qt 5.9 (https://github.com/Homebrew/homebrew-core/pull/14109). Arch Linux is on the way (https://www.archlinux.org/todo/qt-59-rebuild/). Fixing this simplifies packaging.

## How has this been tested?

* Building KeepassXC with the following command on macOS:
```
$ cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Debug -DWITH_GUI_TESTS=ON -DWITH_DEV_BUILD=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/lib/cmake -DWITH_APP_BUNDLE=OFF ..
```
And then run ```make test```

* Smoke tests: open my database, use KeepassHTTP to automatically enter a password, and get a TOTP token.

## Screenshots (if appropriate):
Looks just the same as previous Qt versions :)

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
-  New feature (non-breaking change which adds functionality)
-  Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- All new and existing tests passed. **[REQUIRED]**
There's an intermittent failure in TestGui. I believe it's not caused by this PR - will create a new issue for that.
- I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
Not applicable on non-Linux
- My change requires a change to the documentation and I have updated it accordingly.
- I have added tests to cover my changes.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks!
